version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./app.dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    links:
      - db
    tty: true
    stdin_open: true
    command: "/usr/bin/python start.py"
  db:
    image: postgres:9.6.8
    restart: unless-stopped
    environment:
      - PGDATA=/pgdata
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db_pgdata:/pgdata
  notebook:
    image: jupyter/scipy-notebook:latest
    volumes:
      - notebook_data:/home/jovyan/work
    command: "start-notebook.sh --NotebookApp.token='${JUPYTER_TOKEN}'"
volumes:
  db_pgdata:
  notebook_data:
