version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./app.dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    links:
      - db
    volumes:
      - ./app:/app
      - ./packages:/usr/local/lib/python3.11/site-packages
      - root_app:/root # for bash history etc
    tty: true
    stdin_open: true
    command: ./docker-start
  db:
    image: postgres:9.6.8
    restart: unless-stopped
    environment:
      - PGDATA=/pgdata
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/pgdata
      - root_db:/root # for bash history etc
  notebook:
    image: jupyter/scipy-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - "./notebook:/home/jovyan/work"
    working_dir: "/home/jovyan/work"
    command: "start-notebook.sh --NotebookApp.token='${JUPYTER_TOKEN}'"
volumes:
  root_app:
  root_db:
  pgdata:
