#!/bin/sh
pip install --no-cache-dir -r /app/requirements.txt

python3 start.py
# RAILS STUFF 
# echo "Generating Spring binstubs"
# bundle exec spring binstub --all
# 
# echo "Clearing logs"
# bundle exec rake log:clear
# 
# echo "Setting up new db if one doesn't exist"
# # bin/rake db:drop
# bundle exec rake db:version 2>/dev/null || bundle exec rake db:setup;
# 
# echo "Removing contents of tmp dirs"
# bundle exec rake tmp:clear
# rm ./tmp/pids/*
# 
# bundle exec rails assets:precompile
# exec bundle exec rails s -p 3000 -b '0.0.0.0'
